name: SonarQube Analysis
on:
  push:
    branches:
      - main
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
    - name: Install SonarQube Scanner
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner.zip
        mv sonar-scanner-4.6.2.2472-linux sonar-scanner
        echo "$(pwd)/sonar-scanner/bin" >> $GITHUB_PATH
    - name: Display current directory and contents for debugging
      run: |
        pwd
        ls -la
        ls -la sonar-scanner/bin
    - name: Run SonarQube analysis with debug logging
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=application \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -X || true
    - name: Display SonarQube analysis log
      run: cat sonar-scanner.log || echo "No log found"   
          
